### PR TITLE
Fix the incorrect Boxer Address in the Boxer client

### LINKED ISSUE #63: [Cleanup] Delete deprecated services
Let's remove the following stuff from here:
- Beast
- Crystal

and associated README files.

### PR DESCRIPTION
**Pull request by s-vitaliy**
Resolves #63

## Scope

Implemented:
 - Removed outdated code
 - Fixed the Boxer URI

## Checklist

- [ ] GitHub issue exists for this change.
- [ ] Unit tests added and they pass.
- [ ] Line Coverage is at least 80%.
- [ ] Review requested on `latest` commit.

### CODE REVIEW

File: src/SnD.ApiClient/Boxer/BoxerTokenProvider.cs [hunk 1]
```diff
@@ -28,7 +28,7 @@ public BoxerTokenProvider(IOptions<BoxerTokenProviderOptions> boxerTokenProvider
    {
       var authorizationProvider = boxerTokenProviderOptions.Value.IdentityProvider
                                   ?? throw new ArgumentNullException(nameof(BoxerTokenProviderOptions.IdentityProvider));
-      this.authProvider = new Uri($"token/{authorizationProvider}", UriKind.Relative);
+      this.authProvider = new Uri($"api/v1/token/{authorizationProvider}", UriKind.Relative);
```
Comment (s-vitaliy) [inline src/SnD.ApiClient/Boxer/BoxerTokenProvider.cs:31]: Actual fix is here

**Review by george-zubrienko — APPROVED** [review]
